version: '3.8'
services:
    db:
        image: ankane/pgvector:latest
        container_name: ovlox-postgres
        environment:
            POSTGRES_USER: ovlox
            POSTGRES_PASSWORD: ovlox
            POSTGRES_DB: ovlox
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
